service: my-serverless-function

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2

functions:
  FaseNueva:
    handler: handler.nuevaFase
    events:
      - http:
          path: fase
          method: post
  TareaNueva:
    handler: handler.nuevaTarea
    events:
      - http:
          path: tarea
          method: post
  ActualizaTarea:
    handler: handler.actualizaTarea
    events:
      - http:
          path: tarea
          method: put
  EliminaTarea:
    handler: handler.eliminarTarea
    events:
      - http:
          path: tarea
          method: delete
